version: '3.8'

services:
  bicycle-insurance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bicycle-insurance-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
